### ISSUE TITLE
LAPACK & BLAS dependencies unnecessary ?

### ISSUE THREAD

**Issue by vmagnin** [jacobwilliams/stl-fortran#2]
I had a problem because I don't have LAPACK & BLAS installed on my PC. I have therefore tried to comment those dependencies in the `fpm.toml`:

```toml
#link = ["lapack", "blas"]
```

And it built successfully and I was able to run the tests.

Removing those unused dependencies would allow more people to test that nice small library.

**Comment by jacobwilliams** [comment]
Yes, I think that was probably a copy and paste from another project. I'll remove it!
